### ISSUE TITLE
Error when the call starts 

### ISSUE THREAD

**Issue by xE-1x** [DevKilo1/FivePD-HostageScenarioCallout#2]
![Screenshot 2024-09-12 213750](https://github.com/user-attachments/assets/6b01cbd3-9fdc-4547-9762-29801bb98bfe)

**Comment by DevKilo1** [comment]
This callout lost its AI capabilities on September 9th of this year, hence the error regarding the connection to our AI server. There was a notification relevant to this event inside the FivePD discord server.
